### ISSUE TITLE
TODO for production

### ISSUE THREAD

**Issue by Juknum** [ae-utbm/sith#16]
In GitLab by @skia on Aug 26, 2016, 21:04

  * [x] Make the trigger to create subscriptions on both sites
  * [x] Make the subscription product type to actually make a subscription
  * [x] Set correct passwords everywhere and generate new SECRET_KEY
  * [x] Generate the right HMAC key for the Eboutic
  * [x] Create a nice forum post with a summary of all the migrated features, and the differences between ae2 and Sith
  * [x] Make the menu bar with the right links on each site
  * [x] Fix the HTTP header issue with the Webcam script
  * [x] Change the index page with something more appropriate
  * [x] Make a footer
  * [x] Change the site URL in the sites framework
  * [x] **Deactivate unattended-upgrades** on ae-web
  * [x] List the people who made some Eboutic payment with the old Sogenactif
  * [x] Make the redirections on the old site's following pages:
    * [x] Subscriptions
    * [x] Counters
    * [x] User registration
    * [x] Launderette
